name: quizapp_fe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.5
  font_awesome_flutter: ^10.8.0
#  intl: ^0.17.0
  intl: ^0.19.0
  oktoast: ^3.3.1
  fluttertoast: ^8.2.2
  http: ^1.2.1
  logging: ^1.2.0
  bcrypt: ^1.1.3
  mailer: ^6.1.0
  image_picker: ^1.1.2
  permission_handler: ^10.2.0
  http_parser: ^4.0.2
  google_fonts: ^6.2.1
  flutter_quill: ^9.2.3
  markdown_quill: ^3.0.1
  image_cropper: ^8.0.2
  fl_chart: ^0.66.2 # kiểm tra pub.dev để lấy phiên bản mới nhất

flutter_native_splash:
  color: "#ffffff"
  image: assets/flash_screen1.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_quizz_app.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/quiz/
    - assets/icons/


